google_home:
  entities:
    - media_player.dans_room_speaker
    - media_player.living_room_speaker
    - media_player.living_room_speaker_2
    - media_player.dons_room_speaker
    - media_player.garage_speaker
    - media_player.kitchen_display
    
    
stairs:
  entities:
    - light.upstairs_hallway
    - light.stairs